// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYJBj4jkd9xaqF5g_kKnQW1x12Rl04zDI',
    appId: '1:227630799882:web:4225e7802ff579f1cd93f3',
    messagingSenderId: '227630799882',
    projectId: 'roumeta-866a8',
    authDomain: 'roumeta-866a8.firebaseapp.com',
    storageBucket: 'roumeta-866a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEPYEeR60jhpYsjZkdLgpkUgz4BrVVhd4',
    appId: '1:227630799882:android:7a06b8cdef4a9c55cd93f3',
    messagingSenderId: '227630799882',
    projectId: 'roumeta-866a8',
    storageBucket: 'roumeta-866a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7LH14pLPjPAEKh2asndy-Oazx6wFHuf8',
    appId: '1:227630799882:ios:d10aa83e87064164cd93f3',
    messagingSenderId: '227630799882',
    projectId: 'roumeta-866a8',
    storageBucket: 'roumeta-866a8.appspot.com',
    iosClientId: '227630799882-q3ovqp3par5rnmj8k9cosnnceot4bn90.apps.googleusercontent.com',
    iosBundleId: 'com.example.projeto',
  );
}
